Remove cookie persistence
owncloud/android pull request #3002
Opened 2020-10-22 12:20 UTC by theScrabi

This will resolve cookie persistence which should solve braking the cookiejar after restarting the app.

2020-10-23 06:33 UTC, abelgardep commented on owncloudApp/src/main/java/com/owncloud/android/services/OperationsService.java
> -        SingleSessionManager.getDefaultSingleton().saveAllClients(this, MainApp.Companion.getAccountType());
Remove the comment by the way

2020-10-23 09:21 UTC, jesmrec commented
This are my first insights about this PR:

- i do not see any cookie accumulation

- After attaching one account, cookies are renewed every time i open the app. But, after some times (no quick open/close, quiet actions), if i close and reopen the app, cookies are not renewed anymore

- Attaching two accounts and switching gives the same behaviour. Initial switches, cookies are renewed with no accumulation in both accounts. After a couple of switches, both accounts keep the cookies they had before

2020-10-27 08:12 UTC, abelgardep requested changes
Tiny change required @theScrabi

2020-10-27 08:12 UTC, abelgardep commented on owncloudApp/src/main/java/com/owncloud/android/services/OperationsService.java
> -        SingleSessionManager.getDefaultSingleton().saveAllClients(this, MainApp.Companion.getAccountType());
Remove the comment by the way.

2020-10-27 12:17 UTC, jesmrec commented
Tested in two different cases

1) Only one account

- In account creation, cookies are received after checking `status.php` and then, sent in the requests. Capabilities' request does not send cookies, so the cookie `oc_sessionPassphrase` used in the session are the one received in the capabilities response. The cookie `oc...` (like `oc794f4ep19m`) is renewed frequently (`PROPFINDS`), sometimes responses return a new value even when the request contain the cookie recently received.  From client perspective this is correct, the cookie renewal is not in this side.

- In app closing/opening: same behaviour

2) More accounts

- Account switching (no closing): when switching to another account, no request is done to `status.php`, so same cookies are used as before. 

From my side:

- No cookie accumulation anymore ✅ 
- Cookies received from server are "reflected" in the following requests ✅ 
- Cookies are correctly switched when account switches ✅ 
- Cookies are not renewed when account switches ❓   (not bad, but... expected?)

2020-10-28 11:52 UTC, theScrabi commented
> Cookies are not renewed when account switches question (not bad, but... expected?)

No. This is bad behaviour. The library is saving cookies based on domain. If two accounts are running on the saim domain. Cookies will leak into other sessions.

The only real solution to all of the cookie issues. Is to make the okHttpClient not be a singleton any more.  Hacking around to make this work with the current situation feels like stitching everything together using bandages.

2020-10-28 12:03 UTC, michaelstingl commented
Multiple accounts on the same instance is a supported use case, and all date (credentials, cache, cookies etc) should be strictly separated. Needs 🍪 -jar per account for example…

2020-10-29 03:29 UTC, merged