Cleanup one way mappers
owncloud/android pull request #3112
Opened 2021-02-22 10:04 UTC by abelgardep

Resolves #3091

2021-02-22 12:41 UTC, davigonz requested changes

2021-02-22 12:41 UTC, davigonz commented on owncloudData/src/main/java/com/owncloud/android/data/authentication/datasources/implementation/OCRemoteAuthenticationDataSource.kt
> +        }.let { userInfo = it.toModel() }
I'd use `toDomain` instead since `toModel` is ambiguous , we can have data model, domain model, UI model...

2021-02-22 12:55 UTC, davigonz approved these changes

2021-02-25 10:46 UTC, JuancaG05 approved these changes

2021-02-25 13:00 UTC, jesmrec commented
No QA needed here. Please move on

2021-02-25 13:00 UTC, merged