[TECHNICAL] Kotlinize PassCodeManager
owncloud/android pull request #3372
Opened 2021-09-03 09:52 UTC by JuancaG05

## Related Issues
App: https://github.com/owncloud/android/issues/3371
_____

## QA

2021-09-06 12:27 UTC, fesave approved these changes
LGTM

2021-09-06 12:54 UTC, abelgardep commented on owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
> +        PassCodeManager.getPassCodeManager()!!.bayPassUnlockOnce()
Try not to add !! here 👍

2021-09-07 07:22 UTC, abelgardep requested changes
Last suggestions before moving it forward @JuancaG05 👍

2021-09-07 07:22 UTC, abelgardep commented on owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PassCodeManager.kt
> +        private set
Does it really need to be a `var` with a `private set`? I mean, is it used out of the passcode manager? Could it be a `private val`?
```suggestion
    private val exemptOfPasscodeActivities: MutableSet<Class<*>> = mutableSetOf(PassCodeActivity::class.java)
```

2021-09-07 07:22 UTC, abelgardep commented on owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PassCodeManager.kt
> +    private val PASS_CODE_TIMEOUT = 1000
This one could be marked as a constant, couldn't it?
```suggestion
    private const val PASS_CODE_TIMEOUT = 1_000
```

2021-09-07 07:22 UTC, abelgardep commented on owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PassCodeManager.kt
> +        activity.startActivity(i)
Let's kotlinize it a little bit more 😉 
```suggestion
        val intent = Intent(appContext, PassCodeActivity::class.java).apply {
            action = PassCodeActivity.ACTION_CHECK
            flags = Intent.FLAG_ACTIVITY_REORDER_TO_FRONT or Intent.FLAG_ACTIVITY_SINGLE_TOP
        }
        activity.startActivity(intent)
    }
```

2021-09-07 07:22 UTC, abelgardep commented on owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PassCodeManager.kt
> +
If it is not needed at the moment, I think we can remove this. We can add it when we need it again, what do you think?

2021-09-07 07:42 UTC, abelgardep approved these changes
LGTM 💯

2021-09-07 16:33 UTC, abelgardep commented
Will be tested within https://github.com/owncloud/android/pull/3361

2021-09-07 16:34 UTC, merged