[FEATURE] Migrate splash screen
owncloud/android pull request #3421
Opened 2021-10-26 12:44 UTC by fesave

## Related Issues
App: #3391 

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

2021-10-29 12:39 UTC, JuancaG05 requested changes
A tiny change only! Good job @fesave 👍

2021-11-02 07:19 UTC, fesave commented on changelog/unreleased/3421
> +A new splash screen has been developed to devices
Done!

2021-11-02 07:21 UTC, JuancaG05 approved these changes

2021-11-18 12:41 UTC, jesmrec commented
Splash screen is correctly built with the new API for Android 12 versions (tested with emulator)

New splash screen is built with the white cloud icon and the dark-blue background. The word `ownCloud`, present in the app icon displayed in the login view, is not part of the splash screen anymore.

OTOH, by checking the attached Android documentation, this feature is still in alpha version:

https://developer.android.com/guide/topics/ui/splash-screen/migrate

so, it's not totally safe to merge it. We could either wait till 2.20 is frozen, just in case it jumps to a stable version, or delay it a bit more till Google makes it stable.

2021-11-29 13:19 UTC, jesmrec commented
Regarding (1).

When browsing to root, the `avatar` endpoint request is done, no matter where do toy come from:

- From first login
- From other account
- Browsing back from any folder
- Using the `Files` tab
- From sharing view
- From settings view

will recheck this

2022-01-13 13:33 UTC, jesmrec commented
released:

`androidx.core:core-splashscreen:1.0.0-beta01`

2026-05-19 15:10 UTC, jesmrec commented
Closed as outdated

2026-05-19 15:10 UTC, closed without merging