Update check server button visibility when connection fails
owncloud/android pull request #3523
Opened 2022-01-26 17:19 UTC by abelgardep

In branded builds, the check server button should be visible only when the connection is not established. Otherwise, it should be hidden. 

__
## QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.20/3523-hide_button_check.md

2022-01-27 09:03 UTC, JuancaG05 requested changes
Good job @abelgardep! Just some comments about this.

2022-01-27 09:03 UTC, JuancaG05 commented on owncloudApp/src/main/res/layout-land/account_setup.xml
> +                        android:theme="@style/Button.Authenticator"
Yes, it was really necessary 😁 👍

2022-01-27 12:25 UTC, abelgardep commented on owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt
> +            binding.centeredRefreshButton.setOnClickListener { checkOcServer() }
Yes, the listener is overridden each time we click on it. I have reverted it, and we will set the listener only at the start.

2022-01-27 13:11 UTC, JuancaG05 approved these changes
Great! @abelgardep 🥇

2022-01-28 14:01 UTC, jesmrec commented
Approved on my side

2022-01-31 07:57 UTC, merged