Remove permission dialog
owncloud/android pull request #3524
Opened 2022-01-27 07:53 UTC by abelgardep

Removing the dialog to ask for read/write storage permission. With scoped storage, we do not need it anymore. We store the files in scoped and we do not need permissions to do it.

_____
## QA

2022-01-27 11:47 UTC, JuancaG05 requested changes
A tiny comment here @abelgardep, good job!

2022-01-27 11:47 UTC, JuancaG05 commented on owncloudApp/src/main/res/values-ar/strings.xml
> +    <string name="local_file_not_found_toast">لم يتم العثور على الملف في نظام الملفات المحلية</string>
It seems that the resource manager in Android Studio adds an indentation when you remove a string resource. This has happened in every file 😅 . Try to reformat the code selecting them all, and if you are not able to, I will approve it 👍

2022-01-27 13:13 UTC, JuancaG05 approved these changes
Good job! @abelgardep

2022-01-31 13:26 UTC, jesmrec commented
I'd add a `Calens` entry, even being not a feature. Just for our internal tracking, since this is an old behaviour change.

2022-02-01 11:07 UTC, jesmrec commented
Approved on my side:

- [x] Dialog removed
- [x] Sync after connecting
- [x] Transfers correctly done 

Tested with Nexus 6P v7, Pixel 2 v11

2022-02-02 09:31 UTC, merged