[New Design] Pattern Screen
owncloud/android pull request #3587
Opened 2022-03-16 12:17 UTC by davcres

## Related Issues
App: #3580 

- [] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here]
_____

## Screenshots
| Old view check pattern | New view check pattern | Old view create pattern | New view create pattern |
|:-:|:-:|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/78238260/158587687-baa2fd9a-78a5-41bd-94b3-4200b9620541.png) | ![image](https://user-images.githubusercontent.com/78238260/158586985-5ac1fd6a-ccae-4fa0-809e-caa6b86b6561.png) |  | ![image](https://user-images.githubusercontent.com/78238260/158586808-056d0671-324d-45bd-a105-0ad35b83a822.png) |

## QA

2022-03-17 12:58 UTC, fesave approved these changes
Excellent work!! LGTM

2022-03-17 12:58 UTC, fesave commented on owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PatternActivity.kt
> +    val binding get() = _binding!!
👏🏻

2022-03-25 13:22 UTC, fesave requested changes
Greeeeeat @davcres!! Some tiny suggestions...

2022-03-25 13:22 UTC, fesave commented on owncloudApp/src/main/res/layout-w600dp/activity_pattern_lock.xml
> +        app:layout_constraintTop_toBottomOf="@+id/error_pattern">
Use `@id` instead of `@+id`

2022-03-25 13:22 UTC, fesave commented on owncloudApp/src/main/res/layout-w600dp/activity_pattern_lock.xml
> +        app:layout_constraintTop_toBottomOf="@+id/explanation_pattern" />
Use `@id` instead of `@+id`

2022-03-25 13:22 UTC, fesave commented on owncloudApp/src/main/res/layout-w600dp/activity_pattern_lock.xml
> +        app:layout_constraintBottom_toTopOf="@+id/patternContainer"
Use `@id` instead of `@+id`

2022-03-25 13:22 UTC, fesave commented on owncloudApp/src/main/res/layout-w600dp/activity_pattern_lock.xml
> +        app:layout_constraintTop_toBottomOf="@+id/header_pattern" />
Use `@id` instead of `@+id`

2022-03-25 13:22 UTC, fesave commented on owncloudApp/src/main/res/layout-w600dp/activity_pattern_lock.xml
> +        app:layout_constraintBottom_toTopOf="@+id/error_pattern"
Use `@id` instead of `@+id`

2022-03-25 13:22 UTC, fesave commented on owncloudApp/src/main/res/layout-w600dp/activity_pattern_lock.xml
> +        app:layout_constraintBottom_toTopOf="@+id/explanation_pattern"
Use `@id` instead of `@+id`

2022-03-28 06:17 UTC, fesave approved these changes
LGTM

2022-03-28 11:49 UTC, jesmrec commented
### (1)

1. Enable pattern lock (no matter with or without biometrical)
2. Open Settings and click on Pattern lock to disable it
3. Enter an incorrect pattern
4. Click on back arrow

Current: back to the same view (pattern lock)
Expected: back to Settings

https://user-images.githubusercontent.com/14894746/160391692-37fafbfd-cea0-4da6-8521-0ce393e5e9e6.mp4

Pixel2 v11, Nexus6P v7
`640c87e6`

2022-03-28 11:53 UTC, jesmrec commented
I've just realised that (1) is not a regression... up to you to fix or moving to a separate issue

2022-03-29 08:30 UTC, jesmrec commented
fix for (1) in https://github.com/owncloud/ios-app/issues/1113#issuecomment-1078804100

2022-03-29 09:08 UTC, jesmrec commented
Approved on my side

2022-03-29 15:13 UTC, merged