[New arch] Sync folder recursively
owncloud/android pull request #3714
Opened 2022-07-12 08:31 UTC by abelgardep

## Related Issues
Implements #3707 
_____

## QA

2022-07-12 08:56 UTC, abelgardep commented
### Current state
Syncs recursively all content when clicking on the circle arrow over a folder.
Refresh folder syncs only already downloaded files within this folder, not recursively

### Known issues
1. Folder synchronization can't be cancelled at the moment. Uploads and Downloads are enqueued but can't be cancelled all at the same time
2. Refresh folder when picking a folder (move/copy/camera uploads path) triggers syncs for already downloaded files in the folder (and probably for av offline files in the future). Not sure if this is an issue, but it may takes longer than expected. Just a refresh could do the work when picking a folder

2022-07-13 16:55 UTC, JuancaG05 requested changes
Nice improvement @abelgardep! 💯 Much better to send a String (`accountName`) than the whole account when it's not necessary 😀
Just a tiny comment about something you removed, well done!

2022-07-13 16:55 UTC, JuancaG05 commented on owncloudApp/build.gradle
> -    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.9.1'
Was this intentional? 🤨 It also bothers me sometimes, but I don't know if you wanted to remove it definitely 😀

2022-07-14 06:24 UTC, JuancaG05 approved these changes
LGTM 👍

2022-07-14 07:05 UTC, merged