[New arch] Fix bottom navigation shortcuts
owncloud/android pull request #3719
Opened 2022-07-21 11:53 UTC by abelgardep

Replace LiveData with Flow/StateFlow and retrieve directly the filtered data from the database.

The final state for the screen is generated by combining 4 other states: FileListOption, AccountName, FolderDisplayed, and SearchFilter. This way, the bottom navigation shortcuts should be fixed and more could be added in the future.

Adding StateFlow also removes some nullability checks we had when retrieving the value from the LiveData.

_____

## QA

2022-08-12 12:58 UTC, JuancaG05 requested changes
Huge improvements in one PR! Just some comments, nice work! 🥇

2022-08-12 12:58 UTC, JuancaG05 commented on owncloudDomain/src/test/java/com/owncloud/android/domain/files/usecases/GetSharedByLinkForAccountAsStreamUseCaseTest.kt
> + * Copyright (C) 2021 ownCloud GmbH.
Ehem hehehe 🤪

2022-08-16 06:42 UTC, abelgardep commented on owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt
> +                        remotePath = ROOT_PATH, owner = currentFolder.owner
I would say that it should be mandatory for >2 parameters, and optional for 2. Can do 👍

2022-08-16 06:54 UTC, abelgardep commented on owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/SortOptionsView.kt
> +        val sharedPreferencesProvider = SharedPreferencesProviderImpl(context)
It is already in the CommonModule, but this is a custom view, and I just replaced the old PreferenceManager with the new one

2022-08-16 12:36 UTC, JuancaG05 approved these changes
Nice job!! 💯  Approved on my side 👍

2022-08-18 08:44 UTC, merged