[Spaces] Spaces available only for fresh accounts
owncloud/android pull request #3914
Opened 2023-02-14 15:59 UTC by abelgardep

## Related Issues
Implements https://github.com/owncloud/android/issues/3906

Library PR (if needed):

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

2023-02-15 08:25 UTC, JuancaG05 requested changes
Some comments here 👍  Good job!

2023-02-15 08:25 UTC, JuancaG05 commented on owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
> +            if (AccountUtils.isFeatureSpacesAllowedForAccount(baseContext, account) && capabilities?.isSpacesAllowed() == true) {
I see this condition is used several times along the code... Could we move it to a method in a common place?

2023-02-15 14:05 UTC, JuancaG05 approved these changes
Ready to QA @jesmrec 🚀

2023-02-15 15:45 UTC, jesmrec commented
AFAICS, nothing to test here. Just a new flag and logic to manage it. It will be tested together with the UI notifications for users to re-attach legacy accounts. CI is green, OK from my side unless you point me to test something else here.

2023-02-16 08:21 UTC, jesmrec commented
## QA

- [X] Add oCIS and oC10 accounts after fresh install -> oCIS accounts shows spaces, oC10 accounts do not show spaces

With oCIS and oC10 account in the device in `master`:

- [X] Update from `master` -> oCIS accounts do not show spaces, oC10 accounts do not show spaces
- [X] Add account after updating ->  oCIS accounts show spaces, oC10 accounts do not show spaces

Approved on my side

2023-02-16 08:23 UTC, merged