Authenticated WebFinger
owncloud/android pull request #3945
Opened 2023-03-01 12:40 UTC by abelgardep

## Related Issues
App: https://github.com/owncloud/android/issues/3943

Library PR (if needed): https://github.com/owncloud/android-library/pull/545

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

2023-03-03 08:32 UTC, JuancaG05 requested changes
Good job @abelgardep! Here I left some suggestions 👍

2023-03-03 08:32 UTC, JuancaG05 commented on owncloudData/src/main/java/com/owncloud/android/data/oauth/repository/OCOAuthRepository.kt
> +    private val webfingerRemoteDatasource: WebfingerRemoteDatasource,
To keep consistency with the rest of datasources, maybe this class should be called `RemoteWebfingerDataSource` and thus this property `remoteWebfingerDataSource`, do you agree?

2023-03-03 08:32 UTC, JuancaG05 commented on owncloudData/src/main/java/com/owncloud/android/data/webfinger/datasources/implementation/OCWebfingerRemoteDatasource.kt
>  class OCWebfingerRemoteDatasource(
If you finally change the name of the interface, rename this consequently as well 😁

2023-03-03 08:32 UTC, JuancaG05 commented on owncloudData/src/main/java/com/owncloud/android/data/webfinger/repository/OCWebfingerRepository.kt
> +    override fun getInstancesFromWebFinger(
I see in some methods or classes you write `WebFinger` and in others `Webfinger`... This is not important at all but I'd try to unify it to be consistent 👍

2023-03-06 08:02 UTC, abelgardep commented on owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/AuthenticationViewModel.kt
> +    val serverInfo: LiveData<Event<UIResult<ServerInfo>>> = _serverInfo
In this case, the livedata is next to the usecase call that will update it.

```
livedata
usecase

livedata
usecase

livedata
usecase
```
So, in this case, I would say that it is not bad at all

2023-03-06 13:56 UTC, JuancaG05 requested changes
Some more renamings and we're done @abelgardep 👍

2023-03-06 13:56 UTC, JuancaG05 commented on owncloudData/src/main/java/com/owncloud/android/data/webfinger/datasources/implementation/OCRemoteWebFingerDatasource.kt
> +    private val webfingerService: WebFingerService,
```suggestion
    private val webFingerService: WebFingerService,
```

2023-03-06 13:56 UTC, JuancaG05 commented on owncloudData/src/main/java/com/owncloud/android/data/webfinger/datasources/implementation/OCRemoteWebFingerDatasource.kt
> +    override fun getInstancesFromAuthenticatedWebfinger(
```suggestion
    override fun getInstancesFromAuthenticatedWebFinger(
```

2023-03-06 13:56 UTC, JuancaG05 commented on owncloudData/src/main/java/com/owncloud/android/data/webfinger/datasources/RemoteWebFingerDatasource.kt
> +    fun getInstancesFromAuthenticatedWebfinger(
```suggestion
    fun getInstancesFromAuthenticatedWebFinger(
```
This should be renamed as well 👍

2023-03-06 13:56 UTC, JuancaG05 commented on owncloudData/src/main/java/com/owncloud/android/data/webfinger/datasources/implementation/OCRemoteWebFingerDatasource.kt
> +            webfingerService.getInstancesFromWebfinger(
In the library as well 😀 
```suggestion
            webfingerService.getInstancesFromWebFinger(
```

2023-03-07 07:26 UTC, JuancaG05 approved these changes
Ready for QA 🚀

2023-03-08 11:16 UTC, butonic approved these changes

2023-03-08 17:21 UTC, jesmrec commented
QA checks

different authentication methods and available idPs

- [X] Basic auth
- [X] OAuth2
- [X] OIDC
- [ ] Webfinger v1 (enterprise)
- [X] oCIS traefik (Webfinger v2)
- [X] oCIS Wopi
- [X] oCIS Keycloak

2023-03-09 07:58 UTC, jesmrec commented
All existing auth methods are working in this PR. New authenticated webfinger works, but current instances have same idP and lookup server. So, this is a first working approach but not the ultimate one. Take this as "testable" version of the feature. 

From my side, it can be merged.

2023-03-09 08:01 UTC, merged