Koin dsl
owncloud/android pull request #3966
Opened 2023-03-13 13:39 UTC by abelgardep

Koin now offer a new kind of DSL keyword that allow you to target a class constructor directly, and avoid to to have type your definition within a lambda expression.

Use [koin constructor dsl](https://insert-koin.io/docs/reference/koin-core/dsl-update/) to inject view models, repositories, data sources etc.. Its a little bit cleaner now, and no need to introduce `get() get() get()` over the whole module.

## QA

2023-08-20 07:50 UTC, abelgardep commented
I think that Koin DSL makes it easier to define the dependencies. It removes some verbosity that we have in the standard way.

If you consider it useful, I can fix the conflicts. Otherwise, close the pull request 👍 

@jesmrec @Aitorbp

2023-08-21 06:53 UTC, jesmrec commented
We are still interested, will not be closed. As usual, time reduced. Thanks a lot.

2023-09-02 17:31 UTC, abelgardep commented
I'm not able to fix the conflicts because I don't have write access to the repository anymore 😢 

I could try to cherry-pick and create a new PR from my fork though. Otherwise, you will need to fix the conflicts yourselves.

So up to you 👍

2023-09-04 07:34 UTC, jesmrec commented
We'll try to fix first. Thanks again for your engagement.

2023-09-04 07:45 UTC, michaelstingl commented
> I don't have write access to the repository anymore 😢

Should be fixed 👍

2023-09-10 20:36 UTC, abelgardep commented
Rebased.

Little consideration: We can't inject over 10 dependencies using koin dsl. For example, that's why I kept `TransfersViewModel` the way it was.

2023-09-12 13:55 UTC, JuancaG05 requested changes
Some tiny comments here @abelgardep 🍻

2023-09-12 13:55 UTC, JuancaG05 commented on owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/LocalDataSourceModule.kt
>      factory<LocalAppRegistryDataSource> { OCLocalAppRegistryDataSource(get()) }
Can't this be converted to the new syntax as well? We just have a `get()`, or am I missing something?

2023-09-12 13:55 UTC, JuancaG05 commented on owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/LocalDataSourceModule.kt
> +    factoryOf(::OCLocalSpacesDataSource) bind LocalSpacesDataSource::class
I think you tried to order them alphabetically, this one is not in its corresponding place then 😃

2023-10-02 16:19 UTC, abelgardep commented
Changes applied and rebased @JuancaG05 🍻

2023-10-03 06:54 UTC, JuancaG05 approved these changes
LGTM! Thanks for your contribution @abelgardep! 🚀

2023-10-03 06:54 UTC, merged