Add space to OCFileWithSyncInfo
owncloud/android pull request #3973
Opened 2023-03-17 07:26 UTC by abelgardep

## Related Issues
App: https://github.com/owncloud/android/issues/3971
_____

## QA

2023-03-17 10:39 UTC, JuancaG05 requested changes
A tiny suggestion here @abelgardep. Also, as mentioned in the issue, now that we have this we can maybe clean the transfers VM, fragment and adapter as well 👍

2023-03-17 10:39 UTC, JuancaG05 commented on owncloudDomain/src/main/java/com/owncloud/android/domain/files/model/OCFileWithSyncInfo.kt
I would change the name of this... Maybe `OCFileWithCompleteInfo`? IMHO, `OCFilePopulated` doesn't convince me since it seems that `OCFile` is the same version but with empty properties, so I don't know. Maybe you can suggest a better name of course 👍

2023-03-22 11:37 UTC, JuancaG05 commented on owncloudDomain/src/main/java/com/owncloud/android/domain/files/model/OCFileWithSyncInfo.kt
Ok, seems this implies too many changes, we can let it stay for the moment

2023-03-22 14:03 UTC, jesmrec commented
Technical one, CI green and basic tests passed. Ready to go.

2023-03-22 14:05 UTC, merged