Feature/thumbnails not loaded first time
owncloud/android pull request #4084
Opened 2023-06-22 10:48 UTC by manuelplazaspalacio

## Related Issues
App: #3959 
- Modified how images load in:
   Spaces
   Files list

Library PR (if needed):

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

2023-06-23 09:06 UTC, JuancaG05 requested changes
Some comments here @manuelplazaspalacio! Nice job! 👍

2023-06-23 09:06 UTC, JuancaG05 commented on owncloudApp/src/main/java/com/owncloud/android/presentation/thumbnails/ThumbnailsRequester.kt
> +package com.owncloud.android.presentation.thumbnails
Let's add the copyright header to this class and, in this case, Abel's name since this was his creation 😁

2023-06-27 10:27 UTC, JuancaG05 approved these changes
Good job @manuelplazaspalacio! Let's move this to QA 🚀

2023-07-10 09:26 UTC, jesmrec commented
### (1)

thumbnails' shape has changed, is this intended @manuelplazaspalacio? 👍 

| master | current |
|:-:|:-:|
|<img width="365" alt="Screenshot 2023-07-10 at 11 23 55" src="https://github.com/owncloud/android/assets/14894746/8a1558f8-ea5d-4f84-b4b1-b759ac0867ac">|![Screenshot 2023-07-10 at 11 16 27](https://github.com/owncloud/android/assets/14894746/30d9d051-75eb-4cda-bf18-80841ceb6012)|

2023-07-10 12:23 UTC, jesmrec commented
### (2)

Check the following steps out:

1. Browse to any folder that contains images
2. Using another client, modify a non-downloaded image
3. Pull to refresh in the app folder

Current: Thumbnail not updated. If the image would be downloaded, thumbnail would have updated.
Expected: If an image is externally modified, thumbnail is also updated regardless of the download status. This is the current's `master` behaviour

Pixel 2 Android 11
`4beaef61`

2023-07-12 12:21 UTC, jesmrec commented
This is approved on my side.

Work to do: apply changes to uploads view to make these changes visible there as well.

2023-07-12 13:36 UTC, merged