[FEATURE REQUEST] Support "per app" language change on Android 13+
owncloud/android pull request #4099
Opened 2023-07-13 07:20 UTC by Aitorbp

## Related Issues
App:

Library PR (if needed):

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

2023-07-19 08:48 UTC, JuancaG05 requested changes
Cool! This will be very useful. I left some suggestions and comments here @Aitorbp 🤠

2023-07-19 08:48 UTC, JuancaG05 commented on changelog/unreleased/4082
This file should be named `4099` 😀

2023-07-19 08:48 UTC, JuancaG05 commented on owncloudApp/src/main/AndroidManifest.xml
> +        android:localeConfig="@xml/locales_config">>
```suggestion
        android:localeConfig="@xml/locales_config">
```
Or am I missing something? 🤔

2023-07-19 08:48 UTC, JuancaG05 commented on owncloudApp/src/main/res/xml/locales_config.xml
Not sure if some variants are included here when their identifier doesn't appear in this list 🤔. For example:

<img width="161" alt="Captura de pantalla 2023-07-19 a las 10 34 49" src="https://github.com/owncloud/android/assets/57049315/fc765264-2cbe-4303-a3a7-2f8d9798fff5">

Not the most populated languages of the app but just not to lose them in this feature. Maybe if you tried and it doesn't work it's not allowed to add them... but I think it's worth it to take a look with a quick research over the Internet or some other quick tests 🚀

2023-07-19 08:48 UTC, JuancaG05 commented on owncloudApp/src/main/res/xml/locales_config.xml
> +    <locale android:name="fr"/> <!-- French (France) -->
This kind of comments are so useful, I like them a lot 💯

2023-07-19 08:48 UTC, JuancaG05 commented on owncloudApp/src/main/res/xml/locales_config.xml
> +</locale-config>
Let's finish with a blank line 👍

2023-07-20 10:27 UTC, Aitorbp commented on owncloudApp/src/main/AndroidManifest.xml
> +        android:localeConfig="@xml/locales_config">>
Done

2023-07-21 07:00 UTC, JuancaG05 requested changes
Last changes here and we'll be ready to go! @Aitorbp

2023-07-21 07:00 UTC, JuancaG05 commented on owncloudApp/src/main/res/xml/locales_config.xml
> +    <locale android:name="as"/> <!-- Assamese (India) -->
We should place here first at least the 3 ultimate fallback languages, these are: `en`, `de` and `es`

2023-07-21 12:55 UTC, JuancaG05 commented on owncloudApp/src/main/res/xml/locales_config.xml
Test comment

2023-07-21 12:56 UTC, JuancaG05 approved these changes
Nice job @Aitorbp! 💯

2023-07-24 07:36 UTC, jesmrec commented
A couple of checks:

- [X] Android 13: Check that `ownCloud` is an available option in  device Settings > System > Languages & input > App Languages
- [X] Android 13: Check that app could be set up in a different languages by using the new option available in Settings > System > Languages & input > App Languages
- [X] Android 13: Check that a missing translation in the chosen language is fallen back to the default system language
- [X] Android < 13: Legacy behaviour: app getting device set up language.

Approved on my side and ready to go!!

2023-07-24 13:15 UTC, JuancaG05 commented on owncloudApp/src/main/res/xml/locales_config.xml
When `bn` is included among the available languages it's not necessary to add its variants, the device will show them

2023-07-27 10:31 UTC, merged