[FEATURE REQUEST] Respect app_provider values from capabilities
owncloud/android pull request #4113
Opened 2023-07-31 10:49 UTC by Aitorbp

## Related Issues
App: https://github.com/owncloud/android/issues/4075

Library PR (if needed):

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

2023-08-01 07:52 UTC, manuelplazaspalacio requested changes
Some change here @Aitorbp

2023-08-01 07:52 UTC, manuelplazaspalacio commented on owncloudData/src/main/java/com/owncloud/android/data/appregistry/OCAppRegistryRepository.kt
> +    private val localCapabilitiesDataSource: LocalCapabilitiesDataSource
Pon una coma aquí.

2023-08-01 07:52 UTC, manuelplazaspalacio commented on owncloudData/src/main/java/com/owncloud/android/data/appregistry/OCAppRegistryRepository.kt
> +        val capabilities =  localCapabilitiesDataSource.getCapabilityForAccount(accountName)//remoteAppRegistryDataSource.getCapabilities(accountName)
Ese código comentado sobra.

2023-08-01 07:52 UTC, manuelplazaspalacio commented on owncloudData/src/main/java/com/owncloud/android/data/appregistry/datasources/RemoteAppRegistryDataSource.kt
> +        appUrl: String?
Una coma ahí.

2023-08-01 09:47 UTC, Aitorbp commented on owncloudData/src/main/java/com/owncloud/android/data/appregistry/OCAppRegistryRepository.kt
> +        val capabilities =  localCapabilitiesDataSource.getCapabilityForAccount(accountName)//remoteAppRegistryDataSource.getCapabilities(accountName)
Done

2023-08-01 09:47 UTC, Aitorbp commented on owncloudData/src/main/java/com/owncloud/android/data/appregistry/datasources/RemoteAppRegistryDataSource.kt
> +        appUrl: String?
Done

2023-08-02 11:12 UTC, manuelplazaspalacio approved these changes

2023-08-02 12:43 UTC, jesmrec commented
Fixed. 

Just tested in the attached demo server with different capability value. Let's give a try and get feedback.

2023-08-03 07:26 UTC, merged