[TECHNICAL] Unit tests for datasources classes - Part 2
owncloud/android pull request #4123
Opened 2023-08-10 09:11 UTC by Aitorbp

## Related Issues
App:

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

2023-08-14 09:08 UTC, manuelplazaspalacio requested changes
Some changes here @Aitorbp

2023-08-14 12:04 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    ), OC_SPACE_PERSONAL.toEntity())
Done

2023-08-14 12:20 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +        isSynchronizing = false
Done

2023-08-14 12:20 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    ), OC_SPACE_PERSONAL.toEntity())
done

2023-08-14 12:20 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    fun `moveFile returns list of OCFile`() {
Done

2023-08-14 12:21 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    fun `saveFilesInFolderAndReturnThem returns list of OCFile`() {
done

2023-08-14 12:22 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    fun `saveFile returns unit`() {
Done

2023-08-14 12:23 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    fun `saveConflict returns unit`() {
Done

2023-08-14 12:25 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    fun `cleanConflict returns exception`() {
done

2023-08-14 12:26 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    fun `deleteFile returns unit`() {
done

2023-08-14 12:27 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    fun `deleteFilesForAccount returns unit`() {
done

2023-08-14 12:27 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    fun `deleteFilesForAccount returns exception`() {
Done

2023-08-14 12:30 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    fun `disableThumbnailsForFile returns unit`() {
done

2023-08-14 12:32 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    fun `updateAvailableOfflineStatusForFile returns unit`() {
done

2023-08-14 12:33 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    fun `updateAvailableOfflineStatusForFile returns exception`() {
done

2023-08-14 12:34 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    fun `saveDownloadWorkerUuid returns exception`() {
done

2023-08-17 08:35 UTC, manuelplazaspalacio commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    ), OC_SPACE_PERSONAL.toEntity())
You forgot the last coma.

2023-08-17 08:54 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
> +    ), OC_SPACE_PERSONAL.toEntity())
Done

2023-08-17 08:57 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCRemoteFileDataSourceTest.kt
> +                replace = true
Done

2023-08-17 08:57 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCRemoteFileDataSourceTest.kt
> +                replace = false
Done

2023-08-17 08:59 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCRemoteFileDataSourceTest.kt
> +    fun `refreshFolder returns a list of OCFile`() {
done

2023-08-17 09:02 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCRemoteFileDataSourceTest.kt
> +                replace = true
Done

2023-08-17 09:02 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCRemoteFileDataSourceTest.kt
> +                spaceWebDavUrl = OC_SPACE_PROJECT_WITH_IMAGE.webUrl
Done

2023-08-17 09:02 UTC, Aitorbp commented on owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCRemoteFileDataSourceTest.kt
> +    fun `readFile returns OCFile`() {
Done

2023-08-17 10:09 UTC, merged