[RELEASE] 4.1
owncloud/android pull request #4139
Opened 2023-08-23 12:48 UTC by Aitorbp

## Related Issues
App: https://github.com/owncloud/android/issues/4111

Library PR (if needed): https://github.com/owncloud/android-library/pull/580

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

2023-08-31 07:59 UTC, manuelplazaspalacio requested changes
One change here @Aitorbp

2023-08-31 07:59 UTC, manuelplazaspalacio commented on owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
> +                        message = it.parseError(getString(R.string.copy_file_error), resources, true)
Add the parameters names.

2023-08-31 08:30 UTC, manuelplazaspalacio approved these changes

2023-09-06 08:22 UTC, closed without merging

2023-09-06 08:22 UTC, jesmrec commented
Replaced by https://github.com/owncloud/android/pull/4153