[BUG] Two logs are displayed when you open the app
owncloud/android pull request #4239
Opened 2023-11-29 15:15 UTC by Aitorbp

## Related Issues
App:https://github.com/owncloud/android/issues/4236

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

2023-11-30 14:10 UTC, JuancaG05 requested changes
Some thing to check here @Aitorbp!

2023-12-01 09:19 UTC, Aitorbp commented on owncloudApp/src/main/java/com/owncloud/android/presentation/logging/LogsListActivity.kt
> +        }
No, it will start logging again when you close the app and re-open: it runs in `MainApp` and `enabledLogging` is `true`.

2023-12-05 16:23 UTC, jesmrec commented on changelog/unreleased/4239
> +When the application is closed from the log files screen (with no files) and the app is reopened, a single log file appears and not two.
"instead of two"

2023-12-13 09:34 UTC, jesmrec commented
> Two log files are displayed when you delete all the logs and close and open the app.

Unfortunately, it happens in a easier way. Just closing the app and opening it again, we have a new log file. No matter the date or deletion of other log files. Looks like this:


https://github.com/owncloud/android/assets/14894746/ac8e15af-4453-4312-adca-0759aa46c802


Reproduced with `292e9910`.

2023-12-13 16:00 UTC, JuancaG05 requested changes
Some changes requested here @Aitorbp

2023-12-13 16:00 UTC, JuancaG05 commented on owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/utils/OCFileLoggingTree.kt
> +            }
We should write quality code as long as we can, free of warnings. In this case, Android Studio is already adding several warnings in this snippet. The method `list()` returns a nullable array, so let's cover that:
```suggestion
            it.list()?.let { logFiles ->
                if (logFiles.isNotEmpty()) {
                    val lastDayDateLogFile = getDayFromLogFileName(logFiles.last())
                    val newDayDateLogFile = getDayFromLogFileName(fileNameTimeStamp)
                    if (lastDayDateLogFile == newDayDateLogFile) {
                        fileNameTimeStamp = getDateFromLogFileName(logFiles.last())
                    }
                }
            }
```

2023-12-14 10:38 UTC, JuancaG05 approved these changes
Much better now!! Approved on my side

2023-12-14 13:28 UTC, jesmrec commented
Please, remove Calens stuff. This is a regression and we have already entry for Logging Changes

2023-12-18 07:48 UTC, merged