[BUG] Doubled app after installing
owncloud/android pull request #4286
Opened 2024-01-17 12:05 UTC by Aitorbp

## Related Issues
App: https://github.com/owncloud/android/issues/4262

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

2024-01-24 12:11 UTC, JuancaG05 requested changes
Check the comments in the calens file, the rest LGTM 👍

2024-01-24 12:11 UTC, JuancaG05 commented on changelog/unreleased/4286
> +Bugfix: Fix doubled app after installing
```suggestion
Bugfix: Doubled app in Recents screen after installing
```

2024-01-24 12:11 UTC, JuancaG05 commented on changelog/unreleased/4286
> +from scratch and we are on the login screen
```suggestion
SplashActivity and FileDisplayActivity are not shown anymore in Recents screen when the application is installed
from scratch and we are on the login screen
```

2024-01-24 12:13 UTC, JuancaG05 commented
BTW, did you try with `android:documentLaunchMode` as mentioned in the documentation (https://developer.android.com/guide/components/activities/recents)? Maybe the `intoExisting` value can do the work...

2024-01-24 13:12 UTC, Aitorbp commented
> BTW, did you try with `android:documentLaunchMode` as mentioned in the documentation (https://developer.android.com/guide/components/activities/recents)? Maybe the `intoExisting` value can do the work...

I tried it but it is not working...

2024-01-25 09:50 UTC, JuancaG05 approved these changes

2024-01-29 10:43 UTC, jesmrec commented
checked with many views by opening "Recents" when such activity is displayed:

Login view -> not in recents
Settings view -> not in recents
File List view -> not in recents
Shares view -> not in recents
Details view -> not in recents
Upload view -> not in recents
Manage accounts view -> not in recents
Previews views -> not in recents
Locking views -> not in recents

Here you have a video, if helps:


https://github.com/owncloud/android/assets/14894746/7a9e3dbe-d880-4f3f-b12b-74f0ebf23aab

2026-05-19 15:26 UTC, closed without merging

2026-05-19 15:26 UTC, jesmrec commented
Closing, waiting for a better idea...