[BUG] Conflict in copy: File without extension
owncloud/android pull request #4294
Opened 2024-01-23 10:11 UTC by Aitorbp

## Related Issues
App: https://github.com/owncloud/android/issues/4222

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

2024-01-23 10:31 UTC, Aitorbp commented
The `startsWith` function will not work with files that lack an extension for the following reason:
If we have a file called `test` and we want to copy this same file to the same folder. The file will behave as follows:

`“test (1)”.startsWith(“test”)`

This function will return `true` and therefore enter the `INVALID_COPY_INTO_DESCENDANT` exception, since the prefix is the same.

The behavior with extension would be the following:

`“test (1).log”.startsWith(“test.log”)`

The` test.log` prefix is not contained in the target therefore it will return `false`. With a folder it has the same behavior, only instead of having an extension it has a slash `/` at the end.

I remove the startsWith condition from the `CopyRemoteFileOperation` class and keep this logic in the `CopyFileUseCase`, where these exceptions are being handled.

2024-01-24 10:25 UTC, JuancaG05 requested changes
Check the comments about the calens file, and go ahead with the other issue after finishing this one

2024-01-24 10:25 UTC, JuancaG05 commented on owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/CopyRemoteFileOperation.kt
> -        }
Ok, but in the use case we don't have the second part of the condition (`sourceSpaceWebDavUrl == targetSpaceWebDavUrl`), and that's why we cannot copy into descendants in different spaces. The solution would be merging this condition in the use case. But that will be addressed in the new created issue:
- https://github.com/owncloud/android/issues/4293

2024-01-24 10:46 UTC, Aitorbp commented on changelog/unreleased/4294
> +it does not work with files that lack an extension. The functionality is handling in CopyFileUseCase.
Done

2024-01-24 10:46 UTC, Aitorbp commented on changelog/unreleased/4294
> +Bugfix: Fixed conflict in copy with file without extension
Done

2024-01-25 07:30 UTC, JuancaG05 approved these changes
LGTM

2024-01-25 12:41 UTC, jesmrec commented
Fixed

2024-01-25 12:41 UTC, jesmrec commented
Dont merge till https://github.com/owncloud/android/pull/4295 is also approved

2024-01-26 09:40 UTC, merged