[BUG] Invalid copy into descendant in different spaces
owncloud/android pull request #4295
Opened 2024-01-24 11:09 UTC by Aitorbp

## Related Issues
App: https://github.com/owncloud/android/issues/4293

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

2024-01-25 08:04 UTC, JuancaG05 requested changes

2024-01-25 11:52 UTC, Aitorbp commented on owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/CopyFileUseCase.kt
> +        if (listOfFilesToCopy.any { targetFolder.remotePath.startsWith(it.remotePath) and (targetFolder.spaceId == it.spaceId) }) {
Changed.

2024-01-25 11:53 UTC, Aitorbp commented on changelog/unreleased/4295
> +you want to copy works correctly.
Changed.

2024-01-25 11:53 UTC, Aitorbp commented on changelog/unreleased/4295
> +Bugfix: Copy folder to another space correctly
Changed.

2024-01-25 12:14 UTC, JuancaG05 approved these changes
LGTM now 👍

2024-01-26 08:31 UTC, jesmrec commented
Fixed.

No weird cases were found.

2024-01-26 09:09 UTC, merged