[TECHNICAL] Upgrade min SDK to Android 7.0 (v24)
owncloud/android pull request #4299
Opened 2024-01-26 11:58 UTC by Aitorbp

## Related Issues
App:https://github.com/owncloud/android/issues/4230

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

2024-02-16 09:55 UTC, JuancaG05 requested changes
One tiny change here and ready to go! @Aitorbp

2024-02-16 09:55 UTC, JuancaG05 commented on owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/cursors/FileCursor.kt
> +        flags = flags or Document.FLAG_SUPPORTS_MOVE
You can put this all together with the flags that don't require condition checks, the ones for delete and rename

2024-02-16 10:41 UTC, JuancaG05 requested changes
We can safely remove the `ShareLinkToDialog.java` class as well, since it is not used anymore

2024-02-20 07:41 UTC, JuancaG05 approved these changes
LGTM

2024-02-20 08:41 UTC, jesmrec commented
Some basic checks performed: installation, not installation in Android 6 and, video preview and share sheet.

Everything OK from my side to move forward.

2024-02-20 12:10 UTC, merged