[RELEASE] 4.2.0
owncloud/android pull request #4306
Opened 2024-02-05 12:27 UTC by Aitorbp

## Related Issues
App: https://github.com/owncloud/android/issues/4254
_____

## QA

- [x] (1) Crash after upgrading with logs enabled https://github.com/owncloud/android/pull/4306#issuecomment-1929685063 [FIXED]
- [x] (2) Entries missing in release notes or changelog https://github.com/owncloud/android/pull/4306#issuecomment-1932029335 [FIXED]
- [x] (3) Deeplinks not opened after clearing cache https://github.com/owncloud/android/pull/4306#issuecomment-1932600625 [WONT FIX]

2024-02-05 12:50 UTC, jesmrec commented on owncloudApp/src/main/res/values/strings.xml
> +    <string name="release_notes_4_2_0_subtitle_2">A link that points to the app will open the app and then, resolve the file to preview it directly</string>
add a short note to clarify that shared files are not included yet

2024-02-05 12:51 UTC, jesmrec commented on owncloudApp/src/main/res/values/strings.xml
Add the password policy new feature
Set the minor bugfixing the latest item

2024-02-05 13:09 UTC, jesmrec requested changes

2024-02-05 13:09 UTC, jesmrec commented on owncloudApp/src/main/res/values/strings.xml
> +    <string name="release_notes_4_2_0_subtitle_1">The 4.2.0 version of the app will be the last one that supports Android 6.0</string>
Don't mention the release number (4.2.0), it could be confusing for users that don't track the releases. Just `Current release will be the last...`

2024-02-05 13:59 UTC, JuancaG05 requested changes
Some more changes suggested here @Aitorbp

2024-02-05 13:59 UTC, JuancaG05 commented on owncloudApp/src/main/res/values/strings.xml
> +    <string name="release_notes_4_2_0_title_1">Latest version with support for Android 6.0</string>
To avoid confusions I would say Android 6, there were versions after 6.0 which also have SDK 23

2024-02-05 13:59 UTC, JuancaG05 commented on owncloudApp/src/main/res/values/strings.xml
> +    <string name="release_notes_4_2_0_title_1">Latest version with support for Android 6.0</string>
Also, this is not an `ENHANCEMENT` anymore, it should be `CHANGE`

2024-02-05 13:59 UTC, JuancaG05 commented on owncloudApp/src/main/res/values/strings.xml
> +    <string name="release_notes_4_2_0_title_3">"Share to" in oCIS accounts allows to upload to any space</string>
Instead of oCIS, use `Infinite Scale`

2024-02-05 13:59 UTC, JuancaG05 commented on owncloudApp/src/main/res/values/strings.xml
> +    <string name="release_notes_4_2_0_title_8">Manage password policy in live mode</string>
Only in Infinite Scale accounts

2024-02-06 07:34 UTC, JuancaG05 approved these changes

2024-02-06 13:51 UTC, jesmrec commented
### (1)

1. Install latest stable version `4.1.1`
2. Enter in `Settings` > `Logging` > enable logs
3. Update to current version

Current: app crashes just after opening
Expected: no crash, migration completed

Seems to be a problem with the date format. This is the stacktrace:

```
FATAL EXCEPTION: main
                 Process: com.owncloud.android.debug, PID: 22679
                 java.lang.RuntimeException: Unable to create application com.owncloud.android.MainApp: java.text.ParseException: Unparseable date: "2024-02-06"
                 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
                 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loop(Looper.java:223)
                 	at android.app.ActivityThread.main(ActivityThread.java:7656)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                 Caused by: java.text.ParseException: Unparseable date: "2024-02-06"
                 	at java.text.DateFormat.parse(DateFormat.java:362)
                 	at com.owncloud.android.lib.common.utils.OCFileLoggingTree.<init>(OCFileLoggingTree.kt:68)
                 	at com.owncloud.android.lib.common.utils.OCFileLoggingTree.<init>(OCFileLoggingTree.kt:37)
                 	at com.owncloud.android.lib.common.utils.LoggingHelper.startLogging(LoggingHelper.kt:38)
                 	at com.owncloud.android.providers.LogsProvider.startLogging(LogsProvider.kt:45)
                 	at com.owncloud.android.MainApp.startLogsIfEnabled(MainApp.kt:239)
                 	at com.owncloud.android.MainApp.onCreate(MainApp.kt:99)
                 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
                 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
                 	at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
                 	at android.os.Handler.dispatchMessage(Handler.java:106) 
                 	at android.os.Looper.loop(Looper.java:223) 
                 	at android.app.ActivityThread.main(ActivityThread.java:7656) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```
Pixel2 Android11
Samsung Tab A8 Android 13
`65b3bccda`

2024-02-07 13:15 UTC, jesmrec commented
### (2)

Not a technical one: i realised that our changelog/release notes are not complete. Some contributions from community are missing there:

https://github.com/owncloud/android/pull/4263
https://github.com/owncloud/android/pull/4183
https://github.com/owncloud/android/pull/4177

2024-02-07 17:28 UTC, jesmrec commented on owncloudApp/src/main/res/values/strings.xml
> +    <string name="release_notes_4_2_0_subtitle_9">The network library has been archived and integrated into the application architecture as a module</string>
Archiving network library repository is not something interesting for final users. Only useful in our internal changelog.

2024-02-07 17:38 UTC, jesmrec commented on owncloudApp/src/main/res/values/strings.xml
> +    <string name="release_notes_4_2_0_subtitle_10">Media3 is the new home for Exoplayer, which has become a part of this library</string>
Release notes should avoid technical terms like `Exoplayer` or `Media3`. Final users don't matter about library names and its integration. Just let users know which is the improvement, like `Video player improved` or something similar.

2024-02-07 17:39 UTC, jesmrec commented on owncloudApp/src/main/res/values/strings.xml
> +    <string name="release_notes_4_2_0_title_11">Prevent two media is playing at the same time</string>
not clear IMO, i'd say `Prevent that two media files are playing...`

2024-02-07 17:40 UTC, jesmrec commented
about (2), added some comments to the newly added entries.

2024-02-07 18:06 UTC, jesmrec commented
### (3)

a very weird behaviour:

1. Create a deeplink over any item in oCiS account (not tested with oC10)
2. Click the link to check that it opens the app and the correct file or folder
3. Go to device Settings > Apps > ownCloud
4. Clear cache and storage
5. Click again on the link of step 2

Current behaviour:

`Unknown error`. Also, i noticed that the spaces warning `ocis_accounts_warning_message` is displayed 

Pixel2 Android11
Samsung Tab A8 Android 13
`f54a7cee2`

2024-02-09 12:41 UTC, JuancaG05 commented
(3) was due to the malfunction of the "Clear data" option, which put the database in a weird inconsistent state. But this is not a regression, so it was solved temporally by disabling the `Clear data` button and we'll work on it in a separate issue

2024-02-12 07:59 UTC, jesmrec commented
Release `4.2.0` is approved on my side.

Approved commit: `25de31ec8`

Android Studio version: `Android Studio Hedgehog | 2023.1.1 Patch 2`

Devices:

Pixel2, Android11
Samsung Galaxy Tab A8, Android13

Regression Test: https://github.com/owncloud/QA/blob/master/Mobile/Android/Executions/Release_4.2/RegressionTest.md
Autom test execution vs oC 10.13.4: https://reports.cucumber.io/reports/68cb56b4-7f3b-444b-96dd-405c5bb95093
Autom test execution vs oCIS5: https://reports.cucumber.io/reports/5b315360-af4e-460d-ab43-82f0d8905603

Great job, team!!

2024-02-13 15:02 UTC, merged