[BUG] Retried successful uploads don't free space in /tmp folder
owncloud/android pull request #4341
Opened 2024-03-15 12:23 UTC by Aitorbp

## Related Issues
App:

- [ ] Add changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
- [ ] Add feature to Release Notes in `ReleaseNotesViewModel.kt` creating a new `ReleaseNote()` with String resources (if required)

_____

## QA

2024-03-27 16:32 UTC, JuancaG05 requested changes
Just a change in wording in calens and the release note and ready to go @Aitorbp

2024-03-27 16:32 UTC, JuancaG05 commented on changelog/unreleased/4341
> +Temporary files related to an upload are deleted after the retried successful uploads is finished.
```suggestion
Temporary files related to a failed upload are deleted after retrying it and being successfully completed.
```

2024-03-27 16:32 UTC, JuancaG05 commented on owncloudApp/src/main/res/values/strings.xml
> +    <string name="release_notes_4_3_0_subtitle_7">Temporary files related to an upload are deleted after the retried successful uploads is finished</string>
```suggestion
    <string name="release_notes_4_3_0_subtitle_7">Temporary files related to a failed upload are deleted after retrying it and being successfully completed</string>
```

2024-04-01 09:38 UTC, JuancaG05 approved these changes
LGTM

2024-04-02 07:29 UTC, jesmrec commented
### (1)

1. Enable auto uploads and fill up all the fields
2. Select `kept in original folder` in `Original file will be`
3. Take same pictures from camera
4. Switch server off (or any other condition that makes upload file, except removing device connection)
5. Wait 15 minutes till uploads are enqueued (check in uploads view)
6. When uploads are enqueued and failed, switch server on (or recover the condition that made them fail)
7. Retry all

Current:

When all uploads are finished after the 2nd try, the `/tmp` folder contains all the uploaded files. They are not removed.

Expected:

After the 2nd try with success, all files are removed from the `/tmp` folder

Pixel 2 Android11
Galaxy Tab A8, Android 13
`8cba150e0`

2024-04-02 16:35 UTC, jesmrec commented
|| 1st try success ✅  | 1st try fail :x:<br>2nd try success ✅ |1st & 2nd try fail ❌ <br>3rd try success ✅  |
|:-:|:-|:-|:-|
| **Manual uploads** | **Result**: <br>**/tmp**: <br>**Device**:  |  **Result**: <br>**/tmp**: <br>**Device**: |  **Result**: <br>**/tmp**: <br>**Device**:  |
| **3rd party app upload** | **Result**: <br>**/tmp**: <br>**Device**:  |  **Result**: ✅ <br>**/tmp**: cleaned up ✅ <br>**Device**: Files kept ✅ |  **Result**: ✅ <br>**/tmp**: cleaned up ✅ <br>**Device**: Files kept ✅ |
| **Auto upload (keep)** | **Result**: <br>**/tmp**:  <br>**Device**: Files kept   |   **Result**: ✅ <br>**/tmp**: cleaned up ✅ <br>**Device**: Files kept ✅  |   **Result**: ✅ <br>**/tmp**: cleaned up ✅ <br>**Device**: Files kept ✅ |
| **Auto upload (move)** | **Result**: <br>**/tmp:** <br>**Device**:  |  **Result**: ✅ <br>**/tmp:** cleaned up ✅ <br>**Device**: Files removed ✅|  **Result**: ✅ <br>**/tmp**: cleaned up ✅ <br>**Device**: Files removed ✅|
| **Picture Upload** | **Result**: <br>**/tmp**: <br>**Device**:  | **Result**: <br>**/tmp**: <br>**Device**:  |  **Result**: <br>**/tmp**: <br>**Device**: |

2024-04-04 06:14 UTC, jesmrec commented
Approved on my side

Take the chart above as reference of the uploads behaviour in reference to the internal storage.

2024-04-04 10:26 UTC, merged