[FIX] Disabled spaces are listed
owncloud/android pull request #4406
Opened 2024-05-17 12:04 UTC by joragua

## Related Issues
App: https://github.com/owncloud/android/issues/4405

- [ ] Add changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
- [ ] Add feature to Release Notes in `ReleaseNotesViewModel.kt` creating a new `ReleaseNote()` with String resources (if required)

_____

## QA

2024-05-20 12:39 UTC, JuancaG05 requested changes
Nice! We just need to remove calens here @joragua 🚀

2024-05-20 12:39 UTC, JuancaG05 commented on changelog/unreleased/4406
This is regressive so we don't need a calens here 😉

2024-05-21 08:52 UTC, joragua commented on changelog/unreleased/4406
Done ✅

2024-05-21 09:48 UTC, JuancaG05 approved these changes
LGTM!!

2024-05-21 12:18 UTC, jesmrec commented
Checked in the three main cases for spaces listing:

- List of spaces
- Folder picker in oCIS for copy operation
- Sharing from 3rd party app to oCIS account

In every of them, checking listing and filtering with some disabled spaced.

That's OK from my side

2024-05-21 12:25 UTC, merged