[a11y] 11.1.4.3 Contrast (minimum)
owncloud/android pull request #4429
Opened 2024-06-25 12:52 UTC by Aitorbp

## Related Issues
App:

- [ ] Add changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
- [ ] Add feature to Release Notes in `ReleaseNotesViewModel.kt` creating a new `ReleaseNote()` with String resources (if required)

_____

## QA

2024-07-01 11:45 UTC, Aitorbp commented
Everything related to the toolbar will be done in this issue: https://github.com/owncloud/android/issues/4365.
The avatar change does not apply to Android.

2024-07-02 12:10 UTC, Aitorbp commented
The `list_item_lastmod_and_filesize_text` color has been changed to meet minimum contrast requirements. This color is present in the main file list of the app and also appears in:

- Log list (subtitle): Log size
- Transfer list (subtitles and icons)
- Subtitle bottom sheet file

FYI @jesmrec

2024-07-02 12:44 UTC, JuancaG05 requested changes
Some changes required here @Aitorbp

2024-07-02 12:44 UTC, JuancaG05 commented on owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/FileListAdapter.kt
> +                    setTextColor(ContextCompat.getColor(context, R.color.accessibility_grey_color))
Why doing it programatically?

2024-07-02 12:44 UTC, JuancaG05 commented on owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
> +            getAccountQuotaText()?.setTextColor(getColor(R.color.accessibility_grey_color))
Same, why doing it programmatically?

2024-07-02 14:02 UTC, Aitorbp commented
The `list_item_lastmod_and_filesize_text` color have been changed for this  hex value  `#707575 `to meet with the requirements:

<img width="400" alt="list_item_lastmod_and_filesize_text" src="https://github.com/owncloud/android/assets/34248951/90e6af19-72a0-46cb-acfc-b85b2ccc854a">



Also we have created a new color `share_warning_text` (`#616465`) for public link warning description to meet the requirements:

<img width="400" alt="share_warning_text" src="https://github.com/owncloud/android/assets/34248951/af209fa2-fa58-4c86-af7f-5c1c85ce3e58">


Contrast checked used: https://webaim.org/resources/contrastchecker/

2024-07-02 14:03 UTC, Aitorbp commented on owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/FileListAdapter.kt
> +                    setTextColor(ContextCompat.getColor(context, R.color.accessibility_grey_color))
Changed to the XML: `list_footer`

2024-07-02 14:04 UTC, Aitorbp commented on owncloudApp/src/main/res/values/colors.xml
> +    <color name="accessibility_grey_color">#616465</color>
`list_item_lastmod_and_filesize_text` changed by lighter grey

2024-07-02 14:04 UTC, Aitorbp commented on owncloudApp/src/main/res/layout/share_file_layout.xml
> +                android:textColor="@color/accessibility_grey_color"
`accessibility_grey_color` reference deleted

2024-07-02 14:06 UTC, Aitorbp commented on owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
> +            getAccountQuotaText()?.setTextColor(getColor(R.color.accessibility_grey_color))
Added in XML `nav_drawer_footer`

2024-07-03 06:51 UTC, JuancaG05 approved these changes
LGTM

2024-07-03 10:53 UTC, jesmrec commented
QA checks:

### date and size in list of files

Contrast: `#707575` vs `#FFFFFF` ➡️  4.68 > 4.50 ✅ 

### drawer footer (quota)

Contrast: `#707575` vs `#FFFFFF` ➡️  4.68 > 4.50 ✅ 

### land-drawer footer (quota)

Contrast: `#707575` vs `#FFFFFF` ➡️  4.68 > 4.50 ✅ 

### list footer (#files & #folders)

Contrast: `#707575` vs `#FFFFFF` ➡️  4.68 > 4.50 ✅ 

### shared file size 

Contrast: `#707575` vs `#FFFFFF` ➡️  4.68 > 4.50 ✅ 

### warning public link

Contrast: `#525757` vs `#E0E0E0` ➡️  5.56 > 4.50 ✅ 

### expiration date in public link 

Contrast: `#707575` vs `#FFFFFF` ➡️  4.68 > 4.50 ✅ 

### folder picker - target folder with no writing permissions

Contrast: `#525757` vs `#E0E0E0` ➡️  5.56 > 4.50 ✅ 

### folder picker - share from 3rd party app to folder with no writing permissions

Contrast: `#525757` vs `#E0E0E0` ➡️  5.56 > 4.50 ✅ 

### log size

Contrast: `#707575` vs `#FFFFFF` ➡️  4.68 > 4.50 ✅ 

### upload list: status, size, date, account, space and target folder

Contrast: `#707575` vs `#FFFFFF` ➡️  4.68 > 4.50 ✅ 

### bottom sheet: date and size

Contrast: `#707575` vs `#FFFFFF` ➡️  4.68 > 4.50 ✅ 

tested all views in portrait/landscape orientation.

Also, i took a look to the high contrast mode, which look is much better than before. Moving forward an accessible app step by step 💯 

This is approved from my side.

2024-07-03 11:08 UTC, merged