[FEATURE REQUEST] oCIS Users light
owncloud/android pull request #4518
Opened 2024-11-26 07:36 UTC by joragua

## Related Issues
App: https://github.com/owncloud/android/issues/4490

- [x] Add changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
- [x] Add feature to Release Notes in `ReleaseNotesViewModel.kt` creating a new `ReleaseNote()` with String resources (if required)

_____

## QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Executions/Release_4.5/No%20Personal%20space.md

Reports:

- [x] (1) No feedback in automatic uploads for User Light https://github.com/owncloud/android/pull/4518#issuecomment-2505949167 [FIXED]
- [x] (2) Crash when user light copies file https://github.com/owncloud/android/pull/4518#issuecomment-2506005142 [FIXED]
- [x] (3) Bad navigation in upload https://github.com/owncloud/android/pull/4518#issuecomment-2506081067 [FIXED]
- [X] (4) List not displayed when sharing from 3rd party app  https://github.com/owncloud/android/pull/4518#issuecomment-2507340303 [MOVED to https://github.com/owncloud/android/issues/4522]
- [x] (5) Account in automatic uploads are not set https://github.com/owncloud/android/pull/4518#issuecomment-2507867727 [FIXED]
- [x] (6) Account in automatic upload change when new account is set https://github.com/owncloud/android/pull/4518#issuecomment-2517138844 [FIXED]

2024-11-26 09:44 UTC, joragua commented
### COMPLETED TASKS ✅ 

- Added a condition to support light users in the login
- Created a new fragment to show an empty folder in `Personal` tab
- Disabled refresh from av. offline view
- Updated drawer and manage accounts for light users
- Modified automatic uploads for light users (if there are only light users, automatic uploads are disabled. On the other hand, light accounts are removed from accounts list)
- Modified `ReceiveExternalFiles`
- Added a new condition to avoid oCIS accounts warning dialog for light users

2024-11-27 17:01 UTC, JuancaG05 requested changes
Good job here @joragua! Some comments and questions before we proceed to QA 👍

2024-11-27 17:06 UTC, joragua commented on changelog/unreleased/4518
> +oCIS light users (users without personal space) have been supported in the app
Changed! 😄

2024-11-27 17:07 UTC, joragua commented on owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainEmptyListFragment.kt
> +        with(binding.emptyDataParent) {
Done ✅

2024-11-27 17:12 UTC, joragua commented on owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainEmptyListFragment.kt
> +            listEmptyDatasetTitle.setText(R.string.file_list_empty_title_all_files)
They are necessary because, in `item_empty_dataset.xml`, all visual elements are set with `tools:...` label and not with `android:...`

2024-11-27 17:14 UTC, joragua commented on owncloudApp/src/main/res/values/strings.xml
> +    <string name="light_users_subtitle">Personal folder is not available</string>
Yeah, that's right! Changed!

2024-11-27 17:17 UTC, joragua commented on owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
> +                                   )
Removed 😄

2024-11-27 17:19 UTC, joragua commented on owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
> +    private fun initAndShowEmptyPersonalFolder() {
As you said in a previous comment, it's better to use `Space` because it is only possible with oCIS accounts (in which we have spaces). Changed!

2024-11-28 07:26 UTC, joragua commented on owncloudApp/src/main/java/com/owncloud/android/presentation/settings/automaticuploads/SettingsPictureUploadsFragment.kt
> +    }
Changed!

2024-11-28 07:36 UTC, joragua commented on owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
> +                        getUserQuotasUseCase(Unit)
Done! ✅

2024-11-28 08:24 UTC, joragua commented on owncloudApp/src/main/res/layout/main_empty_list_fragment.xml
> +<androidx.coordinatorlayout.widget.CoordinatorLayout
I've used the same xml that is used in `shares_fragment.xml` to keep consistency

2024-11-28 08:26 UTC, joragua commented on owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
> -                    if (mParents.size() == 1 && personalSpace == null) {
Added the condition `!areSpaceAllowed `

2024-11-28 09:53 UTC, joragua commented on owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
> +                    mReceiveExternalFilesViewModel.areSpacesAllowed(getAccount().name);
Now, when you select an account,  a new `ReceiveExternalFilesViewModel` is created with his capabilities so it isn't necessary to call that method to refresh them

2024-11-28 10:56 UTC, JuancaG05 approved these changes
LGTM, moving to QA!

2024-11-28 11:57 UTC, jesmrec commented
### (1)

1. Login with a User Light in oCIS
2. In `Settings` try to enable automatic uploads

**Current**:

Not posible, and no feedback why

**Expected**:

Not posible, but user should know why (snackbar, subtitle..)

Xiaomi Redmi Note 13
Android 14
`69e545e34`

2024-11-28 12:27 UTC, jesmrec commented
### (2)

1. User light with at least one space
2. Enter in the space and select `Copy` for any file -> list of spaces is displayed
3. Select any space

**Current:**

App crashes. This is the stacktrace:

```
FATAL EXCEPTION: main (Ask Gemini)
                 Process: com.owncloud.android.debug, PID: 21197
                 java.lang.ClassCastException: com.owncloud.android.ui.activity.FolderPickerActivity cannot be cast to com.owncloud.android.ui.activity.FileDisplayActivity
                 	at com.owncloud.android.presentation.files.filelist.MainFileListFragment$subscribeToViewModels$1.invokeSuspend(MainFileListFragment.kt:319)
                 	at com.owncloud.android.presentation.files.filelist.MainFileListFragment$subscribeToViewModels$1.invoke(Unknown Source:8)
                 	at com.owncloud.android.presentation.files.filelist.MainFileListFragment$subscribeToViewModels$1.invoke(Unknown Source:4)
                 	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:214)
                 	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:13)
                 	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:4)
                 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
                 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:8)
                 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:4)
                 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
                 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
                 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:33)
                 	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:398)
                 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(Merge.kt:27)
                 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Unknown Source:8)
                 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Unknown Source:4)
                 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                 	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
                 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(Merge.kt:25)
                 	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
                 	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
                 	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
                 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:376)
                 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                 	at androidx.lifecycle.RepeatOnLifecycleKt$repeatOnLifecycle$3$1$1$1.onStateChanged(RepeatOnLifecycle.kt:106)
                 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
                 	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
13:21:27.651  E  	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313) (Ask Gemini)
                 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
                 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
                 	at androidx.fragment.app.Fragment.performStart(Fragment.java:3176)
                 	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:588)
                 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
                 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
                 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1819)
                 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
                 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:224)
                 	at android.os.Looper.loop(Looper.java:318)
                 	at android.app.ActivityThread.main(ActivityThread.java:8763)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
                 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@17a752, Dispatchers.Main.immediate]
```

**Expected:**

No crash


Xiaomi Redmi Note 13
Android 14
`69e545e34`

2024-11-28 13:05 UTC, jesmrec commented
### (3)

Related with navigation

1. A user light with edit permissions enters in any space with edit permissions
2. Click on FAB -> Upload
3. Upload some files

**Current:**

`Personal` is displayed (the new fragment), but `Spaces` selected in the bottom bar:

https://github.com/user-attachments/assets/583e886b-8f6a-4d84-b37a-c55a94727d4d

**Expected:**

Space's list of files is displayed with the new files uploaded

Xiaomi Redmi Note 13
Android 14
`254d09323`

2024-11-29 08:46 UTC, jesmrec commented
### (4)

1. Enter in a 3rd party app
2. Share something with any user (light or not), inside an space (not `Personal`)

**Current:**

empty list in the picker, but not in every space of every account... that's strange

https://github.com/user-attachments/assets/86878a92-3a2e-40e7-81f1-671a10c35b1a

**Expected:**

list of files inside the space is displayed.

Xiaomi Redmi Note 13
Android 14
`b064986`

2024-11-29 09:23 UTC, jesmrec commented
Note that (4) is also reproducible in current `master`, so it's not something from this PR and does not need to be fixed here.

It is not reproducible in `stable` so this is a regression that must be fixed in the scope of the current version.

2024-11-29 13:54 UTC, jesmrec commented
### (5) (improvement)

1. Add two accounts: user light and regular user
2. Go to `Settings` and enable automatic uploads

**Current:**

`Account to upload pictures` as `Not set` . 

**Expected**:

One account should be set as target when automatic uploads are enabled. Otherwise, the uploads will not have a target to upload and fail with a  non-recoverable `Connection error`

Xiaomi Redmi Note 13
Android 14
`b064986`

2024-12-02 10:35 UTC, joragua commented
**(2) (3)** and **(5)** should be fixed @jesmrec

2024-12-04 11:37 UTC, jesmrec commented
Report (4) was moved to https://github.com/owncloud/android/issues/4522, because it's not a matter of the current PR

2024-12-04 11:58 UTC, jesmrec commented
### (6)

1. Add a non-user light account (a regular one)
2. In Settings, enable automatic uploads -> current account set as default target
3. Add another account to the app

Current

In Settings > automatic uploads, the newly added account is set as target

Expected:

the target account of automatic uploads should be only changed by the user. The account set in step 2. must keep.

Xiaomi Readmi 13
Android 14
`4f3409b0b`

2024-12-04 12:46 UTC, jesmrec commented
Approved on my side 💯

2024-12-04 12:47 UTC, merged